### ISSUE TITLE
Two Authentication method

### ISSUE THREAD

**Issue by Sauasmast** [Raashul/medium-service#5]
There will two approach to authenticate to the user one using the password they provided and one using the google authentication. It would be great if someone could teach me how to verify the email address does exists or not? I want to integrate this feature so please don't delete it. Help will be highly appreciated I will try to implement it if not on my own.

**Comment by Raashul** [comment]
what exactly do you need help with??
-if user tries to sign in with local auth - find if email exists in user table and update. @Sauasmast

**Comment by Sauasmast** [comment]
Done. Now user can login with the local as well as the google auth.
