### ISSUE TITLE
sign in and signup

### ISSUE THREAD

**Issue by Sauasmast** [Raashul/medium-service#6]
What if the user has already signed up with the google then they should be redirect to the old account with the new token instead of the error message. Check it out. 

<img width="703" alt="screen shot 2018-10-31 at 10 39 11 pm" src="https://user-images.githubusercontent.com/16581422/47829430-d6c91700-dd5d-11e8-9d6c-73d3d3044e21.png">

Please take a look. I might be wrong too. 
LOL!!!

**Comment by Raashul** [comment]
do you mean user already exists though google sign in? and tries to sign in again locally? Then error is fine. Redirect to login page.
-If user already has account and tries to SIGN UP again, error should say account already exists. try to log in.

**Comment by Sauasmast** [comment]
I am sorry I got it wrong. LOL. Sorry for the trouble.
