### ISSUE TITLE
Could not add a post form the google authenticated users. 

### ISSUE THREAD

**Issue by Sauasmast** [Raashul/medium-service#7]
The google authenticated users payload data doesnot have a pk as notified in the database. The foreign key will be null and could not add the post from the users authenticated with google. 
<img width="1118" alt="screen shot 2018-10-31 at 11 36 25 pm" src="https://user-images.githubusercontent.com/16581422/47831222-02e89600-dd66-11e8-9835-04165754e481.png">

Rectify the error. 
For upcoming days.

**Comment by Raashul** [comment]
what are you using as PK ?
-When user logs in, store the id generated somewhere globally in backend. 

There shouldn't be any difference if user logs in though email or locally. In the end its the same user info we are trying to get.

**Comment by Sauasmast** [comment]
This is for myself...I am reminding myself about the issue I will solve it. Dont worry about this one.

**Comment by Sauasmast** [comment]
Resolve on the new branch. Ready for merge.

**Comment by Sauasmast** [comment]
Resolved issue on the new branch. Ready for merge.
